language: python
python:
  - "2.7.10"

env:
  - TOXENV=py27

# command to install dependencies
install:
  - "pip install coveralls"
  - "pip install tox"
# command to run tests
script: tox

after_success:
  - coveralls
