language: python
python:
  - "2.7.10"
# command to install dependencies
install: 
  - "pip install -r requirements-dev.txt"
  - "pip install coveralls"
# command to run tests
script:
  - make test
  - make cov
after_success:
  - coveralls
